version: 2
plan:
  project-key: FEAAS
  key: FEAASAT
  name: FEAAS-Acceptance-Tests

variables: !include variables.yaml

stages:
  - variables:
      - calculate-version
  - test:
      jobs:
        - run-acceptance-tests

run-acceptance-tests: !include jobs/run-ui-acceptance-tests.yaml
calculate-version: !include jobs/calculate-version.yaml

triggers:
  - !include triggers/after-dev-deployment.yaml
  - !include triggers/after-qa-deployment.yaml
  - !include triggers/after-preprod-deployment.yaml
  - !include triggers/after-staging-deployment.yaml
  #  - !include triggers/after-prod-deployment.yaml

branches: !include branches/for-new-branch.yaml
other:
  concurrent-build-plugin: '1'
